### ISSUE TITLE
Support for a newer version of libthrift

### ISSUE THREAD

**Issue by ChetanBhasin** [intenthq/sbt-thrift-plugin#12]
Thanks for the wonderful plugin! Do you see any scope for updating the support for a newer version of Thrift?

**Comment by nathankleyn** [comment]
Hey @ChetanBhasin!

Looking now at the README, I've realised we have skipped perhaps the most important aspect of this plugin!

This plugin doesn't, in fact, have _any_ direct dependency on Thrift via `libthrift` or otherwise — this means you're free to use whatever version of the library you like!

Instead, we use `thrift` as installed on your local system (we shell out, effectively) when doing codegen and it's up to you to:

* Install `thrift` onto your local system at the version you need.
* Add the dependency you need on `libthrift`.

This is for some weird reason not covered by the README so I'll add something there ASAP because it's a silly miss on our behalf - so thanks so much for bringing this to our attention! 👍 

For what it's worth, the reason we do it this way is that there are a lot of different "common" versions of Thrift in use out there in the wild. Three examples:

* Lots of people like to use Thrift for RPC between their (micro)services - normally these people will be using the latest version (currently `0.12.0`).
* Lots of people are using Spark to write Parquet Thrift files, which [has a provided dependency on `0.9.3` still as of the latest version](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/2.4.0).
* [MVNRepository shows a good distribution of dependencies on other versions](https://mvnrepository.com/artifact/org.apache.thrift/libthrift) outside of the two above.

So we decided to couple only to the CLI, and in our experience it has been a good choice because it hasn't changed across releases since we first implemented this plugin (`0.780`) until now (`0.12.0`). We've tested this works by using it extensively on internal projects across these upgrades.

To make sure this definitely works, I've added some tests for this plugin in #13 [using the new SBT plugin test framework "scripted"](https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html) which means Travis CI will now ensure it always works on the latest version of Thrift automatically. I'll also explore adding a matrix for other more common versions of Thrift (for example, the one Spark depends on, because it _is_ so common).

Hope this helps you on your way, but if you have any more questions feel free to let us know! 👌

**Comment by nathankleyn** [comment]
Hey @ChetanBhasin! Just a quick update to say the things above have been merged now, so hopefully is more obvious from the `README` and the associated tests. 🤞 

Let me know if you have any more questions!

**Comment by ChetanBhasin** [comment]
Perfect, thanks for the quick turnaround!
